language: sh

os:
  - windows

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

jobs:
  include:
    - name: "Python 2.7 on Windows"
      python: "2.7"
      before_install:
        - set -e
        - . install.sh
        - install_windows_make
        - install_windows_py27
        - init_venv python
    - name: "Python 3.5 on Windows"
      python: "3.5"
      before_install:
        - set -e
        - . install.sh
        - install_windows_make
        - install_windows_py35
        - init_venv python
    - name: "Python 3.6 on Windows"
      python: "3.6"
      before_install:
        - set -e
        - . install.sh
        - install_windows_make
        - install_windows_py36
        - init_venv python
    - name: "Python 3.7 on Windows"
      python: "3.7"
      before_install:
        - set -e
        - . install.sh
        - install_windows_make
        - install_windows_py37
        - init_venv python

install:
  - python --version
  - make develop
before_script:
  - export DEBUG=1
  - export SERVER_FIXTURES_JENKINS_WAR=
  # Select all packages with the Windows classifier
  - export PACKAGES=$(./foreach.sh --quiet 'grep -q Windows setup.py && echo $PKG || true')
script:
  - make test-ci
after_script:
  - bash -c "! compgen -G 'FAILED-*'"

cache:
  directories:
    - ~/AppData/Local/pip/Cache

git:
  depth: false
  submodules: false
