/* Generated by {file} - do not edit! */
/* Inspired by 'Modules/python.c' from main Python distribution */

#include "Python.h"
#include <locale.h>

#ifdef __FreeBSD__
#include <floatingpoint.h>
#endif

#ifndef PyMODINIT_FUNC    /* declarations for DLL import/export */
#if PY_MAJOR_VERSION >= 3
    #define PyMODINIT_FUNC PyObject*
#else
    #define PyMODINIT_FUNC void
#endif
#endif

#if PY_MAJOR_VERSION >= 3
  #define MOD_ERROR_VAL NULL
  #define MOD_SUCCESS_VAL(val) val
  #define MOD_INIT_FUNC(name) PyInit_##name
  #define MOD_DEF(ob, name, doc, methods) \
          static struct PyModuleDef moduledef = {{ \
            PyModuleDef_HEAD_INIT, name, doc, -1, methods, }}; \
          ob = PyModule_Create(&moduledef);
#else
  #define MOD_ERROR_VAL
  #define MOD_SUCCESS_VAL(val)
  #define MOD_INIT_FUNC(name) init##name
  #define MOD_DEF(ob, name, doc, methods) \
          ob = Py_InitModule3(name, methods, doc);
#endif

#define MOD_INIT(name) PyMODINIT_FUNC MOD_INIT_FUNC(name)(void)

{declare};

#ifdef MS_WINDOWS
int
wmain(int argc, wchar_t **argv)
#else
int
main(int argc, char **argv)
#endif
{{
    int res;

    {init};

    Py_Initialize();
    res = PyRun_SimpleString({alias});

    if (res != 0) {{
        fprintf(stderr, "Error creating import aliases\n");
        return 1;
    }}

    /* 754 requires that FP exceptions run in "no stop" mode by default,
     * and until C vendors implement C99's ways to control FP exceptions,
     * Python requires non-stop mode.  Alas, some platforms enable FP
     * exceptions by default.  Here we disable them.
     */
#ifdef __FreeBSD__
    fp_except_t m;

    m = fpgetmask();
    fpsetmask(m & ~FP_X_OFL);
#endif

#if PY_MAJOR_VERSION >= 3
    wchar_t **argv_copy = (wchar_t **)PyMem_Malloc(sizeof(wchar_t*)*(argc+1));
    /* We need a second copies, as Python might modify the first one. */
    wchar_t **argv_copy2 = (wchar_t **)PyMem_Malloc(sizeof(wchar_t*)*(argc+1));
    int i;
    char *oldloc;

    if (!argv_copy || !argv_copy2) {{
        fprintf(stderr, "out of memory\n");
        return 1;
    }}
    oldloc = strdup(setlocale(LC_ALL, NULL));
    setlocale(LC_ALL, "");
    for (i = 0; i < argc; i++) {{
        argv_copy[i] = _Py_char2wchar(argv[i], NULL);
        if (!argv_copy[i]) {{
            free(oldloc);
            fprintf(stderr, "Fatal Python error "
                            "unable to decode the command line argument #%i\n",
                            i + 1);
            return 1;
        }}
        argv_copy2[i] = argv_copy[i];
    }}
    argv_copy2[argc] = argv_copy[argc] = NULL;

    setlocale(LC_ALL, oldloc);
    free(oldloc);
    res = Py_Main(argc, argv_copy);
    for (i = 0; i < argc; i++) {{
        PyMem_Free(argv_copy2[i]);
    }}
    PyMem_Free(argv_copy);
    PyMem_Free(argv_copy2);
#else
    res = Py_Main(argc, argv);
#endif
    Py_Finalize();
    return res;
}}
